name: Build nx3d and publish to PyPi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: curl -sSL https://install.python-poetry.org | python3 -
        name: Install poetry
      - run: poetry build
        name: Build wheel
      - run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
        name: Publish wheel to PyPi
